### ISSUE TITLE
Renaming Simple-Java-Projects

### ISSUE THREAD

**Issue by thiloshon** [Mozilla-Campus-Club-IIT/Simple-Java-Projects#1]
Shall we rename Simple-Java-Projects to Java-Projects and have sub directories for easy, medium and hard tasks? This way all Java related projects will be in the same directory. Its easy for students to explore and choose projects.

**Comment by Supun94** [comment]
Hi @thiloshon , Please use "Labels" for update difficulty levels. We're planning to add few Java projects before the event and using the same directory would not be possible. Each repository contains issues and READ.ME file with the problem.
